# Generated by Django 2.2.16 on 2020-09-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_auto_20200906_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='otp',
        ),
    ]
