# Generated by Django 2.2.16 on 2020-09-08 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0009_auto_20200908_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 4, 21, 3, 597823)),
        ),
    ]
