# Generated by Django 2.2.16 on 2020-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0014_auto_20200908_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.CharField(max_length=70),
        ),
    ]
