# Generated by Django 2.2.16 on 2020-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0015_auto_20200908_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=70),
        ),
    ]
