# Generated by Django 2.2.16 on 2020-09-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0016_auto_20200908_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='otp',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 14, 4, 41, 230243)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.CharField(max_length=60),
        ),
    ]
