# Generated by Django 2.2.16 on 2020-09-08 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0017_auto_20200908_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 17, 56, 17, 457588)),
        ),
    ]
