# Generated by Django 2.2.16 on 2020-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0019_auto_20200908_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=107),
        ),
        migrations.AlterField(
            model_name='verification',
            name='otp',
            field=models.CharField(max_length=107),
        ),
    ]
