# Generated by Django 2.2.16 on 2020-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0020_auto_20200908_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=107),
        ),
        migrations.AlterField(
            model_name='verification',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
